create table if not exists public.consult_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  desired_model text,
  join_type text not null check (join_type in ('번호이동', '기기변경', '신규가입')),
  source text not null default 'linkbus.kr',
  status text not null default 'new'
);

alter table public.consult_requests enable row level security;

drop policy if exists "Anyone can submit consult requests" on public.consult_requests;
create policy "Anyone can submit consult requests"
  on public.consult_requests
  for insert
  to anon
  with check (true);
